@extends('layouts.app')
@section('title','Pengajuan Saya') @section('page-title','Pengajuan Saya') @section('page-subtitle','Ajukan izin, sakit, atau cuti kepada Admin')
@section('content')
<div class="split-grid"><form method="POST" enctype="multipart/form-data" action="{{ route('user.ketidakhadiran.store') }}" class="card form-card">@csrf<div class="card-head"><div><h3>Buat Pengajuan</h3><p>Lengkapi periode dan alasan ketidakhadiran.</p></div></div><div class="form-stack">
<label>Jenis Pengajuan *<select name="jenis" id="jenis" onchange="toggleProof()" required><option value="">Pilih jenis</option><option value="izin">Izin</option><option value="sakit">Sakit</option><option value="cuti">Cuti</option></select></label>
<label>Kategori Alasan *<input name="kategori_alasan" placeholder="Contoh: Urusan keluarga / Sakit demam" required></label><div class="form-grid"><label>Tanggal Mulai *<input type="date" name="tanggal_mulai" min="{{ today()->format('Y-m-d') }}" required></label><label>Tanggal Selesai *<input type="date" name="tanggal_selesai" min="{{ today()->format('Y-m-d') }}" required></label></div><label>Alasan Lengkap *<textarea name="alasan" rows="4" placeholder="Jelaskan alasan pengajuan Anda..." required></textarea></label><label id="proofField" style="display:none">Bukti Sakit *<input type="file" name="file_bukti" id="fileBukti" accept=".jpg,.jpeg,.png,.pdf"><small>JPG, PNG, atau PDF. Maksimal 3 MB.</small></label><button class="btn btn-primary btn-block">Kirim Pengajuan</button></div></form>
<div class="card"><div class="card-head"><div><h3>Riwayat Pengajuan</h3><p>Status keputusan dari Admin</p></div></div><div class="request-history">@forelse($pengajuan as $p)<div class="history-item"><div class="history-top"><div><strong>{{ ucfirst($p->jenis) }} — {{ $p->kategori_alasan }}</strong><small>{{ $p->tanggal_mulai->format('d M Y') }} sampai {{ $p->tanggal_selesai->format('d M Y') }}</small></div><span class="badge {{ $p->status_pengajuan }}">{{ ucfirst($p->status_pengajuan) }}</span></div><p>{{ $p->alasan }}</p>@if($p->catatan_admin)<div class="admin-note"><strong>Catatan Admin:</strong> {{ $p->catatan_admin }}</div>@endif</div>@empty<div class="empty">Belum ada pengajuan.</div>@endforelse</div></div></div>
@endsection
@push('scripts')<script>function toggleProof(){const sick=document.getElementById('jenis').value==='sakit';document.getElementById('proofField').style.display=sick?'flex':'none';document.getElementById('fileBukti').required=sick}</script>@endpush
