@extends('layouts.app')
@section('title','Dashboard User') @section('page-title','Halo, '.$pegawai->nama.'!') @section('page-subtitle','Catat kehadiranmu dengan GPS dan foto langsung')
@section('content')
<div class="user-hero"><div><span class="eyebrow">STATUS HARI INI</span><h2>{{ $hariIni ? ($hariIni->jam_pulang?'Presensi hari ini sudah lengkap':'Sudah presensi masuk') : 'Belum melakukan presensi' }}</h2><p>{{ $lokasi? $lokasi->nama_lokasi.' • Radius '.$lokasi->radius_meter.' meter' : 'Lokasi presensi belum diatur Admin' }}</p></div><div class="live-clock"><strong id="clock">--:--:--</strong><span>{{ now()->translatedFormat('d F Y') }}</span></div></div>
<div class="user-grid">
<div class="card attendance-card"><div class="card-head"><div><h3>Presensi Sekarang</h3><p>Aktifkan GPS dan izinkan akses kamera</p></div><span id="gpsStatus" class="badge pending">GPS belum aktif</span></div>
@if($lokasi)
<form method="POST" action="{{ route('user.presensi.store') }}" id="attendanceForm">@csrf<input type="hidden" name="aksi" id="aksi"><input type="hidden" name="latitude" id="latitude"><input type="hidden" name="longitude" id="longitude"><input type="hidden" name="akurasi" id="akurasi"><input type="hidden" name="foto" id="foto">
<div class="camera-box"><video id="video" autoplay playsinline></video><canvas id="canvas" hidden></canvas><div id="cameraPlaceholder"><span>◎</span><strong>Kamera belum aktif</strong><small>Klik tombol di bawah untuk memulai</small></div></div>
<div class="location-info"><span>⌖</span><div><strong id="locationText">Mendeteksi lokasi...</strong><small id="accuracyText">Pastikan GPS perangkat aktif</small></div></div>
<div class="attendance-actions"><button type="button" class="btn btn-soft" id="cameraBtn" onclick="startCamera()">Aktifkan Kamera</button>@if(!$hariIni)<button type="button" class="btn btn-primary" onclick="submitAttendance('masuk')">Presensi Masuk</button>@elseif(!$hariIni->jam_pulang)<button type="button" class="btn btn-primary" onclick="submitAttendance('pulang')">Presensi Pulang</button>@else<button type="button" class="btn btn-soft disabled" disabled>Presensi Selesai</button>@endif</div></form>
@else<div class="empty">Lokasi presensi belum tersedia. Hubungi Admin.</div>@endif</div>
<div class="side-stack"><div class="card today-card"><div class="card-head"><div><h3>Hari Ini</h3><p>Ringkasan presensi</p></div></div><div class="time-pair"><div><span>Jam Masuk</span><strong>{{ $hariIni?->jam_masuk?substr($hariIni->jam_masuk,0,5):'--:--' }}</strong></div><div><span>Jam Pulang</span><strong>{{ $hariIni?->jam_pulang?substr($hariIni->jam_pulang,0,5):'--:--' }}</strong></div></div>@if($hariIni)<span class="badge {{ $hariIni->status }}">{{ ucfirst($hariIni->status) }}</span>@endif</div>
<div class="card quick-card"><h3>Butuh izin?</h3><p>Ajukan izin, sakit, atau cuti dan pantau persetujuan Admin.</p><a class="btn btn-primary btn-block" href="{{ route('user.ketidakhadiran.index') }}">Buat Pengajuan @if($pengajuanAktif)<span class="count">{{ $pengajuanAktif }}</span>@endif</a></div></div></div>
<div class="card mt"><div class="card-head"><div><h3>Riwayat Terbaru</h3><p>Tujuh presensi terakhir Anda</p></div></div><div class="table-wrap"><table><thead><tr><th>Tanggal</th><th>Status</th><th>Jam Masuk</th><th>Jam Pulang</th><th>Jarak Masuk</th></tr></thead><tbody>@forelse($riwayat as $r)<tr><td>{{ $r->tanggal->format('d/m/Y') }}</td><td><span class="badge {{ $r->status }}">{{ ucfirst($r->status) }}</span></td><td>{{ substr($r->jam_masuk,0,5) }}</td><td>{{ $r->jam_pulang?substr($r->jam_pulang,0,5):'–' }}</td><td>{{ round($r->jarak_masuk) }} m</td></tr>@empty<tr><td colspan="5"><div class="empty">Belum ada riwayat presensi.</div></td></tr>@endforelse</tbody></table></div></div>
@endsection
@push('scripts')<script>
let stream=null, locationReady=false;
setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleTimeString('id-ID'),1000);
if(navigator.geolocation){navigator.geolocation.getCurrentPosition(p=>{document.getElementById('latitude').value=p.coords.latitude;document.getElementById('longitude').value=p.coords.longitude;document.getElementById('akurasi').value=p.coords.accuracy;document.getElementById('gpsStatus').textContent='GPS aktif';document.getElementById('gpsStatus').className='badge hadir';document.getElementById('locationText').textContent=p.coords.latitude.toFixed(6)+', '+p.coords.longitude.toFixed(6);document.getElementById('accuracyText').textContent='Akurasi sekitar '+Math.round(p.coords.accuracy)+' meter';locationReady=true},e=>{document.getElementById('locationText').textContent='Lokasi gagal dideteksi';document.getElementById('accuracyText').textContent='Izinkan akses lokasi di browser';},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
async function startCamera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});let v=document.getElementById('video');v.srcObject=stream;v.style.display='block';document.getElementById('cameraPlaceholder').style.display='none';document.getElementById('cameraBtn').textContent='Kamera Aktif'}catch(e){alert('Kamera tidak dapat diakses. Izinkan kamera pada browser.')}}
function submitAttendance(type){if(!locationReady)return alert('GPS belum siap. Aktifkan lokasi lalu coba lagi.');if(!stream)return alert('Aktifkan kamera terlebih dahulu.');let v=document.getElementById('video'),c=document.getElementById('canvas');c.width=640;c.height=480;c.getContext('2d').drawImage(v,0,0,c.width,c.height);document.getElementById('foto').value=c.toDataURL('image/jpeg',.78);document.getElementById('aksi').value=type;if(confirm('Kirim presensi '+type+' sekarang?'))document.getElementById('attendanceForm').submit()}
</script>@endpush
