@extends('layouts.app')
@php($edit=isset($lokasi))
@section('title',$edit?'Edit Lokasi Presensi':'Tambah Lokasi Presensi') @section('page-title',$edit?'Edit Lokasi Presensi':'Tambah Lokasi Presensi') @section('page-subtitle','Tentukan titik presensi dan aturan jam kerja')
@section('content')
<form class="card form-card" method="POST" action="{{ $edit?route('admin.lokasi.update',$lokasi):route('admin.lokasi.store') }}">@csrf @if($edit)@method('PUT')@endif
<div class="form-section"><h3>Informasi Lokasi</h3><p>Gunakan koordinat dari titik lokasi kantor atau area presensi.</p><div class="form-grid">
<label>Nama Lokasi *<input name="nama_lokasi" value="{{ old('nama_lokasi',$lokasi->nama_lokasi??'') }}" required></label><label>Radius Presensi (meter) *<input type="number" name="radius_meter" min="1" max="10000" value="{{ old('radius_meter',$lokasi->radius_meter??100) }}" required></label>
<label>Latitude *<input type="number" name="latitude" step="0.00000001" min="-90" max="90" value="{{ old('latitude',$lokasi->latitude??'') }}" required></label><label>Longitude *<input type="number" name="longitude" step="0.00000001" min="-180" max="180" value="{{ old('longitude',$lokasi->longitude??'') }}" required></label>
<label class="full">Alamat *<textarea name="alamat" rows="3" required>{{ old('alamat',$lokasi->alamat??'') }}</textarea></label></div></div>
<div class="form-section"><h3>Aturan Jam Kerja</h3><p>Waktu mengikuti zona yang dipilih untuk lokasi ini.</p><div class="form-grid"><label>Zona Waktu *<select name="zona_waktu" required>@foreach(['Asia/Jakarta'=>'WIB (Asia/Jakarta)','Asia/Makassar'=>'WITA (Asia/Makassar)','Asia/Jayapura'=>'WIT (Asia/Jayapura)'] as $value=>$label)<option value="{{ $value }}" @selected(old('zona_waktu',$lokasi->zona_waktu??'Asia/Jakarta')===$value)>{{ $label }}</option>@endforeach</select></label><label>Status *<select name="status" required><option value="aktif" @selected(old('status',$lokasi->status??'aktif')==='aktif')>Aktif</option><option value="nonaktif" @selected(old('status',$lokasi->status??'aktif')==='nonaktif')>Nonaktif</option></select></label>
<label>Jam Masuk *<input type="time" name="jam_masuk" value="{{ old('jam_masuk',isset($lokasi)?substr($lokasi->jam_masuk,0,5):'08:00') }}" required></label><label>Batas Terlambat *<input type="time" name="batas_terlambat" value="{{ old('batas_terlambat',isset($lokasi)?substr($lokasi->batas_terlambat,0,5):'08:15') }}" required></label><label>Jam Pulang *<input type="time" name="jam_pulang" value="{{ old('jam_pulang',isset($lokasi)?substr($lokasi->jam_pulang,0,5):'16:00') }}" required></label></div></div>
<div class="form-actions"><a class="btn btn-soft" href="{{ route('admin.lokasi.index') }}">Batal</a><button class="btn btn-primary">{{ $edit?'Simpan Perubahan':'Tambah Lokasi' }}</button></div></form>
@endsection